### ISSUE TITLE
Reconfigure Difficulties

### ISSUE THREAD

**Issue by rbrtbrnschn** [rbrtbrnschn/reAxion#57]
- HighDurationDifficulty
- LowDeviationDifficulty
- UnlimitedLivesBut50%ChanceOfGameOverDifficulty (sounds fun :D)

**Comment by IsaaacQINH** [comment]
- VariableDeviation
- Timer on Guess (3 secs to guess or something like that)

Could also be fun :)

**Comment by rbrtbrnschn** [comment]
> * VariableDeviation
> * Timer on Guess (3 secs to guess or something like that)
> 
> Could also be fun :)

Would love your feedback on the functionality in #62. 
Code needs some refactoring. I'm aware.

**Comment by rbrtbrnschn** [comment]
Additional Difficulties may be requested [here](https://github.com/rbrtbrnschn/reAxion/discussions/50)

**Comment by IsaaacQINH** [comment]
> > * VariableDeviation
> > * Timer on Guess (3 secs to guess or something like that)
> > 
> > Could also be fun :)
> 
> Would love your feedback on the functionality in #62. It's live at https://reaxion-git-refactor-difficulty-strategy-rbrtbrnschn.vercel.app/settings . Code needs some refactoring. I'm aware.

Looking good.
The 3s Timer on guess mode should probably have a ready button for each round or at least the first round. The first suggestion might defeat the purpose of this difficulty, the latter might prevent the case gameover in the first round with no input made.
Also there is a gameover modal in this gamemode on round 1 when guessed wrong or no input was made.
